config/routes.rb
Rails.application.routes.draw do
  resources :smells
  root 'smells#index'

end

app/models/smell.rb
class Smell < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/smells_controller.rb
class SmellsController < ApplicationController

  def index
    @smells = Smell.all
  end

  def show
    @smell = Smell.find( params[:id] )
  end

  def edit
    @smell = Smell.find( params[:id] )
  end

  def new
    @smell = Smell.new
  end

  def create
    @smell = Smell.new smell_params
    if @smell.save
     redirect_to @smell
    else
      render :new
    end
  end

  def update
    @smell = Smell.find( params[:id] )
    if @smell.update( smell_params )
      redirect_to @smell
    else
      render :edit
    end
  end

  def destroy
    @smell = Smell.find( params[:id] )
    @smell.destroy
    redirect_to smells_path
  end

  private

  def smell_params
    params.require(:smell).permit(:title, :image_url, :location_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrbanSmell</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1><%= link_to 'UrbanSmell', root_path %></h1>
  <%= yield %>
</body>
</html>

app/views/smells/_form.html.erb
<%= form_for @smell do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.label :location_url %>
  <%= f.text_field :location_url %>
  <%= f.submit %>
<% end %>

app/views/smells/edit.html.erb
<h2>Edit Smell</h2>

<%= render "form" %>

app/views/smells/index.html.erb
<ul>
  <li><%= link_to 'Create new smell', new_smell_path %></li>
  <% @smells.each do |smell| %>
    <li><%= link_to smell.title, smell %></li>
  <% end %>
</ul>

app/views/smells/new.html.erb
<h2>New Smell</h2>

<%= render 'form' %>

app/views/smells/show.html.erb
&laquo; <%= link_to 'back', smells_path %>
<h1><%= @smell.title %></h1>
<time><%= @smell.updated_at.strftime("%b %d, %Y") %></time><br>
<%= link_to 'View on map', @smell.location_url %>
<br>
<%= image_tag( @smell.image_url ) %>

<hr>
<%= link_to 'Edit', edit_smell_path( @smell ) %>
<%= link_to 'Delete', smell_path( @smell ), method: :delete %>